spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.30.155.55:3306/didaoa?characterEncoding=utf-8
    username: root
    password: 123456
    type: com.mchange.v2.c3p0.ComboPooledDataSource
server:
  tomcat:
    uri-encoding: UTF-8
mybatis:
  type-aliases-package: com.qf.pojo
pagehelper:
  helper-dialect: mysql